apiVersion: v1
kind: Secret
metadata:
  name: frigate-notify
data:
    FN_FRIGATE__MQTT__USERNAME: <base64 decoded mqtt username>
    FN_FRIGATE__MQTT__PASSWORD: <base64 decoded mqtt password>
    FN_FRIGATE__PASSWORD: <base64 password>
    FN_FRIGATE__USERNAME: <base64 username>